apiVersion: v1
kind: Pod
metadata:
  name: microgpu-test-pod
spec:
  restartPolicy: Never  # 执行完成后不重启
  containers:
    - name: qwen-inference
      image: nvcr.io/nvidia/pytorch:24.05-py3
      command: ["sleep", "infinity"]  # 保持容器运行
      resources:
        requests:
          nvidia.com/microgpu: 1
        limits:
          nvidia.com/microgpu: 1
      volumeMounts:
        - name: model-storage
          mountPath: /model
        # 新增nvidia-smi挂载
        - name: nvidia-bin
          mountPath: /usr/local/nvidia/bin  # 容器内标准路径
  volumes:
    - name: model-storage
      hostPath:
        path: /home/Qwen1.5-0.5B-Chat
        type: Directory
    # 新增宿主机二进制挂载
    - name: nvidia-bin
      hostPath:
        path: /usr/bin  # 宿主机nvidia-smi所在目录
        type: Directory
#    - name: cuda-lib
#      hostPath:
#        path: /usr/lib/x86_64-linux-gnu