apiVersion: v1
kind: Pod
metadata:
  name: microgpu-test
spec:
  restartPolicy: OnFailure
  containers:
    - name: test-container
      image: nvidia/cuda:12.4.0-base-ubuntu22.04
      command:
        - "/bin/bash"
        - "-c"
        - |
          # 验证设备可见性
          echo "列出所有设备:"
          /usr/bin/nvidia-smi -L  # 使用完整路径
          echo ""
          echo "MIG 设备详情:"
          /usr/bin/nvidia-smi mig -lgi  # 使用完整路径
          echo ""
          echo "CUDA 设备查询:"
          if [ -f "/usr/local/cuda/extras/demo_suite/deviceQuery" ]; then
            /usr/local/cuda/extras/demo_suite/deviceQuery
          else
            echo "deviceQuery not found, installing cuda-samples..."
            apt update && apt install -y cuda-samples-12-4
            cd /usr/local/cuda/samples/1_Utilities/deviceQuery
            make
            ./deviceQuery
          fi
      resources:
        limits:
          nvidia.com/microgpu: 1