apiVersion: v1
kind: Pod
metadata:
  name: nvidia-test-pod
spec:
  runtimeClassName: nvidia
  restartPolicy: Never
  containers:
    - name: test-container
      image: nvcr.io/nvidia/pytorch:24.05-py3
      imagePullPolicy: IfNotPresent  # 关键修改：优先使用本地镜像
      command: ["nvidia-smi"]
      args: [ "sleep", "infinity" ]
      resources:
        limits:
          nvidia.com/microgpu: 1