# qwen-statefulset-local-direct.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qwen-mini
spec:
  serviceName: "qwen-service"
  replicas: 1
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app: qwen
  template:
    metadata:
      labels:
        app: qwen
    spec:
      terminationGracePeriodSeconds: 120
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - qwen
              topologyKey: kubernetes.io/hostname
      containers:
        - name: text-generation
          image: ghcr.io/huggingface/text-generation-inference:1.4.1
          command: ["/bin/sh", "-c"]
          args:
            - "echo '容器已启动，等待手动调试...'; sleep infinity"  # 只等待不执行
          env:
            - name: TRANSFORMERS_OFFLINE
              value: "1"
            - name: HF_HUB_OFFLINE
              value: "1"
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
          volumeMounts:
            - name: model-storage
              mountPath: /model
      volumes:
        - name: model-storage
          hostPath:
            path: /home/Qwen1.5-0.5B-Chat
            type: Directory
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0

---
apiVersion: v1
kind: Service
metadata:
  name: qwen-service
spec:
  type: NodePort
  selector:
    app: qwen
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080