apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qwen-mini
spec:
  serviceName: "qwen-service"
  replicas: 1
  selector:
    matchLabels:
      app: qwen
  template:
    metadata:
      labels:
        app: qwen
    spec:
      terminationGracePeriodSeconds: 600
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - qwen
              topologyKey: kubernetes.io/hostname
      containers:
        - name: text-generation
          image: ghcr.io/huggingface/text-generation-inference:1.4.1
          command: ["/bin/sh", "-c"]
          args:
            - |
              # 安装兼容的bitsandbytes
              
              # 诊断环境
              echo "===== 环境诊断信息 ====="
              echo "CUDA_HOME: $CUDA_HOME"
              echo "LD_LIBRARY_PATH: $LD_LIBRARY_PATH"
              ls -l $CUDA_HOME
              nvidia-smi
              
              # 启动服务
              text-generation-launcher \
                --model-id /model \
                --num-shard 1 \
                --port 8000 \
                --quantize bitsandbytes
              
              sleep infinity
          env:
            - name: TRANSFORMERS_OFFLINE
              value: "1"
            - name: HF_HUB_OFFLINE
              value: "1"
            - name: NVIDIA_DISABLE_REQUIRE
              value: "1"
            - name: LD_LIBRARY_PATH
              value: "/usr/lib/x86_64-linux-gnu:/usr/local/cuda/lib64:/usr/local/nvidia/lib64"
            - name: CUDA_HOME
              value: "/usr/local/cuda-12.1"
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "compute,utility"
            - name: FORCE_CUDA
              value: "1"
          resources:
            limits:
              nvidia.com/microgpu: 1
            requests:
              nvidia.com/microgpu: 1
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: model-storage
              mountPath: /model
            - name: nvidia-driver-lib
              mountPath: /usr/local/nvidia/lib64
      volumes:
        - name: model-storage
          hostPath:
            path: /home/k8sadmin/Qwen1.5-0.5B-Chat
            type: Directory
        - name: nvidia-driver-lib
          hostPath:
            path: /usr/lib/x86_64-linux-gnu
            type: Directory