# qwen-statefulset-local-direct.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qwen-mini
spec:
  serviceName: "qwen-service"
  replicas: 1
  podManagementPolicy: OrderedReady  # 确保一次只处理一个Pod
  selector:
    matchLabels:
      app: qwen
  template:
    metadata:
      labels:
        app: qwen
    spec:
      terminationGracePeriodSeconds: 120  # 给Pod足够的时间优雅终止
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - qwen
              topologyKey: kubernetes.io/hostname
      containers:
        - name: text-generation
          image: ghcr.io/huggingface/text-generation-inference:1.4.1
          command: ["text-generation-launcher"]
          args:
            - "--model-id"
            - "/model"
            - "--num-shard"
            - "1"
            - "--port"
            - "8000"
#            - "--quantize"
#            - "bitsandbytes"
          env:
            - name: TRANSFORMERS_OFFLINE
              value: "1"
            - name: HF_HUB_OFFLINE
              value: "1"
            - name: NVIDIA_DISABLE_REQUIRE
              value: "1"
            - name: LD_LIBRARY_PATH
              value: /host-lib:/usr/local/nvidia/lib64:/usr/local/nvidia/lib
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
          securityContext: # 添加设备访问权限
            privileged: true
          # 添加就绪探针，确保Pod完全启动后才被认为是就绪
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 10
            timeoutSeconds: 5
          # 添加存活探针，确保应用健康
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
          resources:
            limits:
              nvidia.com/microgpu: 1
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: model-storage
              mountPath: /model
            - name: nvidia-devices
              mountPath: /dev/nvidiactl
            - name: nvidia-devices
              mountPath: /dev/nvidia-uvm
            - name: nvidia-devices
              mountPath: /dev/nvidia-uvm-tools
            - name: nvidia-devices
              mountPath: /dev/nvidia-modeset
            - name: nvidia-libs
              mountPath: /host-lib
      volumes:
        - name: model-storage
          hostPath:
            path: /home/k8sadmin/Qwen1.5-0.5B-Chat
            type: Directory
        - name: nvidia-devices
          hostPath:
            path: /dev
        - name: nvidia-libs
          hostPath:
            path: /usr/lib/x86_64-linux-gnu
  # StatefulSet更新策略
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0  # 确保有序更新

---
apiVersion: v1
kind: Service
metadata:
  name: qwen-service
spec:
  type: NodePort
  selector:
    app: qwen
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080