# qwen-statefulset-local-direct.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qwen-mini
spec:
  serviceName: "qwen-service"
  replicas: 1
  podManagementPolicy: OrderedReady  # 确保一次只处理一个Pod
  selector:
    matchLabels:
      app: qwen
  template:
    metadata:
      labels:
        app: qwen
    spec:
      terminationGracePeriodSeconds: 120  # 给Pod足够的时间优雅终止
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - qwen
              topologyKey: kubernetes.io/hostname
      containers:
        - name: text-generation
          image: ghcr.io/huggingface/text-generation-inference:1.4.1
          command: [ "/bin/sh", "-c" ]
          args:
            - >
              # 检查CUDA可用性
              echo "===== 开始CUDA检查 =====";
              python -c "import torch; print('CUDA available:', torch.cuda.is_available())" > /proc/1/fd/1;
              nvidia-smi > /proc/1/fd/1 2>&1 || echo 'nvidia-smi未找到！';
              echo "===== CUDA检查结束 =====";

              # 运行原始命令（无量化）
              text-generation-launcher --model-id /model --num-shard 1 --port 8000 > /proc/1/fd/1 2>/tmp/error.log;

              # 保持容器运行
              echo "===== 容器进入调试模式 =====";
              sleep infinity
          env:
            - name: TRANSFORMERS_OFFLINE
              value: "1"
            - name: HF_HUB_OFFLINE
              value: "1"
            - name: NVIDIA_VISIBLE_DEVICES
              value: all  # 关键！暴露GPU设备
          volumeMounts:
            - name: model-storage
              mountPath: /model
      volumes:
        - name: model-storage
          hostPath:
            path: /home/Qwen1.5-0.5B-Chat
            type: Directory
  # StatefulSet更新策略
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0  # 确保有序更新

---
apiVersion: v1
kind: Service
metadata:
  name: qwen-service
spec:
  type: NodePort
  selector:
    app: qwen
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080