# nvidia-device-plugin-time-slicing.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nvidia-time-slicing-config
  namespace: kube-system
data:
  time-slicing-config.yaml: |
    version: v1
    sharing:
      timeSlicing:
        resources:
          - name: "nvidia.com/gpu"
            replicas: 4
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-device-plugin-daemonset
  namespace: kube-system
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: nvidia-device-plugin-ds
  template:
    metadata:
      labels:
        name: nvidia-device-plugin-ds
    spec:
      containers:
        - name: nvidia-device-plugin-ctr
          image: nvcr.io/nvidia/k8s-device-plugin:v0.17.2@sha256:037160a36de0f060fc21cc0cb2f795d980282ff1471b55530433ca4350b24c4f
          imagePullPolicy: IfNotPresent
          command: ["nvidia-device-plugin"]
          args: ["--config-file=/etc/nvidia/time-slicing/time-slicing-config.yaml"]
          env:
            - name: FAIL_ON_INIT_ERROR
              value: "false"
            - name: NVIDIA_DEVICE_PLUGIN_LOG_LEVEL
              value: "debug"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - mountPath: /var/lib/kubelet/device-plugins
              name: device-plugin
            - mountPath: /etc/nvidia/time-slicing
              name: time-slicing-config
              readOnly: true
      priorityClassName: system-node-critical
      tolerations:
        - effect: NoSchedule
          key: nvidia.com/gpu
          operator: Exists
      volumes:
        - hostPath:
            path: /var/lib/kubelet/device-plugins
          name: device-plugin
        - name: time-slicing-config
          configMap:
            name: nvidia-time-slicing-config
            items:
              - key: time-slicing-config.yaml
                path: time-slicing-config.yaml
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate